name: Build, Test, and Deploy ASP.NET Core WebApp to Azure

on:
  push:
    branches: [ "main","dev" ]
  pull_request:
    branches: [ "main","dev" ]

env:
  AZURE_WEBAPP_NAME: feedback   # <-- App Service name
  AZURE_WEBAPP_SLOT: staging
  DOTNET_VERSION: '9.0.x'                              # .NET 9 SDK version range

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --no-restore

  migrate_staging_db:
    if: github.ref == 'refs/heads/dev'
    needs: build_and_test
    runs-on: ubuntu-latest

    # Override DefaultConnection for EF tools
    env:
      ConnectionStrings__DefaultConnection: ${{ secrets.AZURE_POSTGRES_CONNECTION_STAGING }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore src/feedbackApp/feedbackApp.csproj

      - name: Install dotnet-ef
        run: dotnet tool install --global dotnet-ef --version 9.0.0

      - name: Add dotnet tools to PATH
        shell: bash
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Apply EF Core migrations to STAGING database
        working-directory: src/feedbackApp
        run: dotnet ef database update --configuration Release


  migrate_prod_db:
    if: github.ref == 'refs/heads/main'
    needs: build_and_test
    runs-on: ubuntu-latest

    env:
      ConnectionStrings__DefaultConnection: ${{ secrets.AZURE_POSTGRES_CONNECTION_PROD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Restore
        run: dotnet restore src/feedbackApp/feedbackApp.csproj

      - name: Install dotnet-ef
        run: dotnet tool install --global dotnet-ef --version 9.0.0

      - name: Add dotnet tools to PATH
        shell: bash
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Apply EF Core migrations to PROD database
        working-directory: src/feedbackApp
        run: dotnet ef database update --configuration Release


  deploy_staging:    
    #run when pushing to dev branch
    if: github.ref == 'refs/heads/dev'
    #needs: build_and_test
    needs: migrate_staging_db   # run only after DB migration succeeds
    runs-on: ubuntu-latest
    env:
      ASPNETCORE_ENVIRONMENT: Staging

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Publish
        run: dotnet publish src/feedbackApp/feedbackApp.csproj -c Release -o ./publish

      - name: Deploy to Azure Web App (staging slot)
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          slot-name: ${{env.AZURE_WEBAPP_SLOT}}
          publish-profile: ${{secrets.AZURE_FEEDBACKAPP_PUBLISH_PROFILE_STAGING}}
          package: ./publish

  
  deploy_production:
    if: github.ref == 'refs/heads/main'
    #needs: build_and_test         # deploy only if build+tests succeed
    needs: migrate_prod_db
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Publish
        run: dotnet publish src/feedbackApp/feedbackApp.csproj -c Release -o ./publish

      - name: Deploy to Azure Web App(production)
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_FEEDBACKAPP_PUBLISH_PROFILE_PROD }}
          package: ./publish
